// Generate src/views/licences.ts from package-lock.json and the installed packages' LICENSE files.
// The About view lists every runtime package with its version and licence, and reproduces each distinct licence text
// unmodified (Apache-2.0 section 4(a)). Run after npm ci: node scripts/gen_licences.mjs
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const lock = JSON.parse(readFileSync(join(root, "package-lock.json"), "utf8"));
const rows = [];
const texts = new Map();
for (const [p, v] of Object.entries(lock.packages)) {
  if (!p || v.dev) continue;
  const name = p.replace(/^.*node_modules\//, "");
  const licence = v.license || "UNKNOWN";
  rows.push({ name, version: v.version, licence });
  const dir = join(root, p);
  if (!existsSync(dir)) continue;
  const file = readdirSync(dir).find((f) => /^(LICENSE|LICENCE|COPYING)(\.(md|txt))?$/i.test(f));
  if (!file) continue;
  const text = readFileSync(join(dir, file), "utf8").trim();
  // One text per licence id; the toolkit's Apache-2.0 file is the plain text, kept as the Apache-2.0 copy.
  const key = licence + (licence === "MIT" || licence.startsWith("BSD") ? ` (${name})` : "");
  if (!texts.has(licence) || (licence === "Apache-2.0" && name === "@blueprintjs/core")) texts.set(licence, { name: `${licence}: ${name === "@blueprintjs/core" ? "the toolkit packages" : name}`, text });
  void key;
}
rows.sort((a, b) => a.name.localeCompare(b.name));
const uniq = [];
const seen = new Set();
for (const r of rows) {
  const k = r.name + "@" + r.version;
  if (seen.has(k)) continue;
  seen.add(k);
  uniq.push(r);
}
const out = `// Generated by scripts/gen_licences.mjs from package-lock.json and the installed LICENSE files. Do not edit by hand.
export const THIRD_PARTY = {
  packages: ${JSON.stringify(uniq, null, 2)} as { name: string; version: string; licence: string }[],
  texts: ${JSON.stringify([...texts.values()], null, 2)} as { name: string; text: string }[],
};
`;
writeFileSync(join(root, "src", "views", "licences.ts"), out);
const counts = {};
for (const r of uniq) counts[r.licence] = (counts[r.licence] || 0) + 1;
console.log(`wrote src/views/licences.ts: ${uniq.length} runtime packages, ${texts.size} licence texts`, counts);
